import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {cn} from "@/lib/utils";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "ECOMIE APP",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={cn(inter.className, 'antialiased bg-deep-forest-green-100 flex items-center justify-center text-white')}>
        <main className='max-w-[1628px] pr-4 pl-4 w-full min-h-screen'>{children}</main>
        </body>
        </html>
    );
}
